// Code generated by kitcom. DO NOT EDIT.

package main

import kittenipc "efprojects.com/kitten-ipc"

type TsIpcApi struct {
	Ipc *kittenipc.KittenIPC
}

func (t *TsIpcApi) Div(
	a int, b int,
) int {
	return t.Ipc.Call(
		"Div", a, b,
	)
}
