// Code generated by kitcom. DO NOT EDIT.

package main

import (
	kittenipc "efprojects.com/kitten-ipc"
	"fmt"
)

type TsIpcApi struct {
	Ipc kittenipc.Callable
}

func (t *TsIpcApi) Div(
	a int, b int,
) (
	int, error,
) {
	results, err := t.Ipc.Call("TsIpcApi.Div", a, b)
	if err != nil {
		return 0, fmt.Errorf("call to TsIpcApi.Div failed: %w", err)
	}
	_ = results
	return results[0].(int), nil
}
