// Code generated by kitcom. DO NOT EDIT.

import { ParentIPC, ChildIPC } from "kitten-ipc";
export default class IpcApi {
  protected ipc: ParentIPC | ChildIPC;

  constructor(ipc: ParentIPC | ChildIPC) {
    this.ipc = ipc;
  }

  async Div(a: number, b: number): Promise<number> {
    const results = await this.ipc.call("IpcApi.Div", a, b);
    return results[0] as number;
  }
}
